name: test

on:
  push:
    branches:
      - 'main'
      - 'next'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redislabs/redistimeseries:edge
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'

      - name: Run tests
        run: go test -v ./...